# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_passwd
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
